    runs-on: ubuntu-latest
    steps:
        name: Bandit Scan
        uses: shundor/bandit-action@v1
    with: 
        path: "."
        level: low
        confidence: high
        exit_zero: true 
